# DC schema
 
# --- !Ups


CREATE TABLE PROJECT (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(255) NOT NULL
);


CREATE TABLE TASK (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COLOR varchar(255) NOT NULL,
    PROJECT integer NOT NULL,
    FOREIGN KEY (PROJECT) REFERENCES PROJECT (ID)
);

CREATE TABLE BASELINE (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(255) NOT NULL,
    REVENUE integer NOT NULL,
    DESCRIPTION text NOT NULL
);

CREATE TABLE BASEVALUE (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BASELINE integer NOT NULL,
    CATEGORY varchar(255) NOT NULL,
    VALUE integer NOT NULL,
    FOREIGN KEY (BASELINE) REFERENCES BASELINE (ID)
);

CREATE TABLE USER (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PROFILE varchar(255) NOT NULL
);

CREATE TABLE VOTE (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BASELINE integer NOT NULL,
    USER integer NOT NULL,
    TIMESTAMP timestamp NOT NULL, #TODO can be null - update
    FOREIGN KEY (BASELINE) REFERENCES BASELINE (ID),
    FOREIGN KEY (USER) REFERENCES USER (ID)
);

CREATE TABLE VOTEVALUE (
    ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BASEVALUE integer NOT NULL,
    VOTE varchar(255) NOT NULL,
    DELTA integer NOT NULL,
    FOREIGN KEY (BASEVALUE) REFERENCES BASEVALUE (ID),
    FOREIGN KEY (VOTE) REFERENCES VOTE (ID)
);


 
# --- !Downs

DROP TABLE PROJECT;
DROP TABLE TASK;
DROP TABLE BASELINE;
DROP TABLE BASEVALUE;
DROP TABLE USER;
DROP TABLE VOTE;
DROP TABLE VOTEVALUE;